[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/themes/dracula"]
    type = "archive"
    # url = "https://api.github.com/repos/dracula/zsh/tarball"
    url = "https://github.com/dracula/zsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
