# This template is run by `chezmoi init` and creates a .chezmoi.toml config file

# Prompt user for their email and store it in data

[data]
  email = "wolf.simon.n@gmail.com"


[keypassxc]
    database = "/Users/snwolf/Dropbox/.keepass/personal_passwords.kdbx"
